package com.example.myapp;

import static com.codename1.ui.CN.*;

import com.codename1.components.SpanLabel;
import com.codename1.fingerprint.Fingerprint;
import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;
import com.codename1.ui.util.Resources;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class MyAppName extends Lifecycle {
    @Override
    public void runApp() {
        Form hi = new Form("Fingerprint", BoxLayout.y());
        if(!Fingerprint.isAvailable()) {
            hi.add("Fingerprint not available...");
        } else {
            Button scanFingerprint = new Button("Scan Fingerprint");
            hi.add(scanFingerprint);
            scanFingerprint.addActionListener(e -> {
                Fingerprint.scanFingerprint(value -> {
                    hi.add("Scan successfull!");
                    hi.revalidate();
                }, (sender, err, errorCode, errorMessage) -> {
                    hi.add("Scan Failed!");
                    hi.revalidate();
                });
            });
        }

        Button savePassword = new Button("Save Password");
        Button getPassword = new Button("Get Password");

        savePassword.addActionListener(e -> storePassword());
        getPassword.addActionListener(e -> fetchPassword());
        hi.add(savePassword);
        hi.add(getPassword);

        hi.show();
    }

    private void storePassword() {
        String account = "steve@example.com";
        String password = "....";

        Fingerprint.addPassword(
                "Adding secure item to keystore", // Message to display in authentication dialog
                account,
                password
        ).onResult((success, err)->{
            if (err != null) {
                Log.e(err);
                Dialog.show("Error", "Failed to add password to keystore: " + err, "OK", null);
            } else {
                // success always true if there was no error.
                Dialog.show("Success", "Successfully added password to keystore", "OK", null);
            }
        });
    }

    private void fetchPassword() {
        Fingerprint.getPassword("Because", "steve@example.com")
                .onResult((String res, Throwable err) -> {
                    Display.getInstance().callSerially(() -> {
                        Dialog.show("Message", "Biometric login testing here 2", "OK", null);
                    });
                });

    }

}
